//
//  ViewController.swift
//  CameraML
//
//  Created by Kviatkovskii on 26.06.17.
//  Copyright © 2017 Kviatkovskii. All rights reserved.
//

import UIKit
import Photos
import SnapKit
import RxSwift
import Lightbox

final class ViewController: UIViewController {

    let cameraController = CameraController()
    
    fileprivate let captureButton: UIButton = {
        let button = UIButton(frame: CGRect(x: 0.0, y: 0.0, width: 50.0, height: 50.0))
        button.backgroundColor = UIColor.white
        button.layer.borderColor = UIColor.black.cgColor
        button.layer.borderWidth = 1.0
        button.layer.cornerRadius = min(button.frame.width, button.frame.height) / 2
        button.addTarget(self, action: #selector(captureImage), for: UIControlEvents.touchUpInside)
        return button
    }()
    
    ///Displays a preview of the video output generated by the device's cameras.
    fileprivate let capturePreviewView: UIView = {
        let view = UIView()
        view.backgroundColor = UIColor.gray
        return view
    }()
    
    fileprivate lazy var openLibraryButton: UIButton = {
        let button = UIButton(frame: CGRect(x: 0.0, y: 0.0, width: 40.0, height: 40.0))
        return button
    }()
    
    fileprivate lazy var toggleCameraButton: UIButton = {
        let button = UIButton(frame: CGRect(x: 0.0, y: 0.0, width: 25.0, height: 25.0))
        let image = #imageLiteral(resourceName: "ic_switch_camera").withRenderingMode(UIImageRenderingMode.alwaysTemplate)
        button.setImage(image, for: .normal)
        button.tintColor = UIColor(white: 1.0, alpha: 1.0)
        button.addTarget(self, action: #selector(switchCameras), for: UIControlEvents.touchUpInside)
        return button
    }()
    
    fileprivate lazy var toggleFlashButton: UIButton = {
        let button = UIButton(frame: CGRect(x: 0.0, y: 0.0, width: 25.0, height: 25.0))
        let image = #imageLiteral(resourceName: "ic_flash_on").withRenderingMode(UIImageRenderingMode.alwaysTemplate)
        button.setImage(image, for: .normal)
        button.tintColor = UIColor(white: 1.0, alpha: 1.0)
        button.addTarget(self, action: #selector(toggleFlash), for: UIControlEvents.touchUpInside)
        return button
    }()
        
    fileprivate func updateConstraints() {
        capturePreviewView.snp.makeConstraints { (make) in
            make.top.bottom.equalToSuperview()
            make.left.right.equalToSuperview()
        }
        
        captureButton.snp.makeConstraints { (make) in
            make.size.equalTo(CGSize(width: 50.0, height: 50.0))
            make.centerX.equalToSuperview()
            make.bottom.equalToSuperview().offset(-25.0)
        }
        
        openLibraryButton.snp.makeConstraints { (make) in
            make.size.equalTo(CGSize(width: 40.0, height: 40.0))
            make.centerY.equalTo(captureButton)
            make.left.equalToSuperview().offset(15.0)
        }
        
        toggleCameraButton.snp.makeConstraints { (make) in
            make.size.equalTo(CGSize(width: 25.0, height: 25.0))
            make.centerY.equalTo(captureButton)
            make.right.equalToSuperview().offset(-15.0)
        }
        
        toggleFlashButton.snp.makeConstraints { (make) in
            make.size.equalTo(CGSize(width: 25.0, height: 25.0))
            make.centerX.equalTo(toggleCameraButton)
            make.right.equalTo(toggleCameraButton)
            make.bottom.equalTo(toggleCameraButton.snp.top).offset(-20.0)
        }
        
        super.updateViewConstraints()
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        getLastPhotoFromLibrary()
        
        self.view.addSubview(capturePreviewView)
        capturePreviewView.addSubview(captureButton)
        capturePreviewView.addSubview(openLibraryButton)
        capturePreviewView.addSubview(toggleCameraButton)
        capturePreviewView.addSubview(toggleFlashButton)
        
        updateConstraints()
        
        configureCameraController()
    }
    
    func configureCameraController() {
        cameraController.prepare { (error) in
            if let error = error {
                print(error)
            }
            
            try? self.cameraController.displayPreview(on: self.capturePreviewView)
        }
    }
    
    func toggleFlash() {
        if cameraController.flashMode == .on {
            cameraController.flashMode = .off
            let image = #imageLiteral(resourceName: "ic_flash_off").withRenderingMode(UIImageRenderingMode.alwaysTemplate)
            toggleFlashButton.setImage(image, for: .normal)
        } else {
            cameraController.flashMode = .on
            let image = #imageLiteral(resourceName: "ic_flash_on").withRenderingMode(UIImageRenderingMode.alwaysTemplate)
            toggleFlashButton.setImage(image, for: .normal)
        }
    }
    
    func switchCameras() {
        do {
            try cameraController.switchCameras()
        } catch {
            print(error)
        }
        
        switch cameraController.currentCameraPosition {
        case .some(.front):
            toggleCameraButton.setImage(#imageLiteral(resourceName: "ic_switch_camera"), for: .normal)
            
        case .some(.rear):
            toggleCameraButton.setImage(#imageLiteral(resourceName: "ic_switch_camera"), for: .normal)
            
        case .none:
            return
        }
    }
    
    func captureImage() {
        cameraController.captureImage { [unowned self] (image, error) in
            guard let image = image else {
                print(error ?? "Image capture error")
                return
            }
            
            do {
                try PHPhotoLibrary.shared().performChangesAndWait {
                    PHAssetChangeRequest.creationRequestForAsset(from: image)
                }
                self.getLastPhotoFromLibrary()
            } catch {
                print(error)
            }
        }
    }
    
    fileprivate func getLastPhotoFromLibrary() {
        let fetchOptions = PHFetchOptions()
        fetchOptions.sortDescriptors = [NSSortDescriptor(key: "creationDate", ascending: true)]
        let fetchResult = PHAsset.fetchAssets(with: .image, options: fetchOptions)

        let requestOptions = PHImageRequestOptions()
        requestOptions.isSynchronous = true
        
        if let lastAsset: PHAsset = fetchResult.lastObject {
            let manager = PHImageManager.default()
            
            manager.requestImage(for: lastAsset,
                                 targetSize: openLibraryButton.bounds.size,
                                 contentMode: .aspectFill,
                                 options: requestOptions,
                                 resultHandler: { [unowned self] (image, _) in
                                    self.openLibraryButton.setImage(image, for: .normal)
            })
        }
    }
}
